using Xunit;
using GrcMvc.Models.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;

namespace GrcMvc.Tests.Unit;

/// <summary>
/// Unit tests for RiskDtos validation and behavior
/// </summary>
public class RiskDtosTests
{
    [Fact]
    public void RiskListItemDto_Create_WithValidData()
    {
        // Arrange
        var id = Guid.NewGuid();
        var riskNumber = "RISK-001";
        var title = "Data Breach Risk";
        var category = "Compliance";
        var status = "Open";
        var inherentScore = 24;
        var residualScore = 18;
        var residualRating = "Critical";
        var responsibleParty = "Security Team";

        // Act
        var risk = new RiskListItemDto
        {
            Id = id,
            RiskNumber = riskNumber,
            Title = title,
            Category = category,
            Status = status,
            InherentScore = inherentScore,
            ResidualScore = residualScore,
            ResidualRating = residualRating,
            ResponsibleParty = responsibleParty,
            IdentifiedDate = DateTime.Now,
            MitigationCount = 3
        };

        // Assert
        Assert.Equal(id, risk.Id);
        Assert.Equal(riskNumber, risk.RiskNumber);
        Assert.Equal(title, risk.Title);
        Assert.Equal(category, risk.Category);
        Assert.Equal(status, risk.Status);
        Assert.Equal(inherentScore, risk.InherentScore);
        Assert.Equal(residualScore, risk.ResidualScore);
        Assert.Equal(residualRating, risk.ResidualRating);
        Assert.Equal(responsibleParty, risk.ResponsibleParty);
        Assert.Equal(3, risk.MitigationCount);
    }

    [Fact]
    public void RiskCreateDto_DefaultValues_SetCorrectly()
    {
        // Act
        var risk = new RiskCreateDto();

        // Assert
        Assert.Empty(risk.Title);
        Assert.Empty(risk.Category);
        Assert.Empty(risk.Description);
        Assert.Equal(0, risk.InherentScore);
        Assert.Equal(0, risk.ResidualScore);
        Assert.Empty(risk.ResponsibleParty);
        Assert.Equal("Medium", risk.Impact);
        Assert.Equal("Medium", risk.Likelihood);
    }

    [Fact]
    public void RiskEditDto_WithAutoGeneratedNumber_DisplaysReadOnly()
    {
        // Arrange
        var risk = new RiskEditDto
        {
            Id = Guid.NewGuid(),
            RiskNumber = "RISK-001",
            Title = "Test Risk",
            Category = "Operational"
        };

        // Act & Assert
        Assert.NotEmpty(risk.RiskNumber);
        Assert.Equal("RISK-001", risk.RiskNumber);
    }

    [Theory]
    [InlineData("Low", true)]
    [InlineData("Medium", true)]
    [InlineData("High", true)]
    [InlineData("Critical", true)]
    [InlineData("Invalid", true)] // Application doesn't validate
    public void RiskDetailDto_ImpactLevels_Accepted(string impact, bool isValid)
    {
        // Act
        var risk = new RiskDetailDto { Impact = impact };

        // Assert
        Assert.Equal(impact, risk.Impact);
    }

    [Fact]
    public void RiskMitigationDto_Create_WithValidData()
    {
        // Arrange
        var riskId = Guid.NewGuid();
        var mitigationId = Guid.NewGuid();

        // Act
        var mitigation = new RiskMitigationDto
        {
            Id = mitigationId,
            RiskId = riskId,
            Title = "Implement Firewall",
            Description = "Deploy new firewall system",
            Status = "In Progress",
            PlannedEffectiveness = 8,
            Owner = "IT Security",
            PlannedDate = DateTime.Now.AddMonths(1)
        };

        // Assert
        Assert.Equal(mitigationId, mitigation.Id);
        Assert.Equal(riskId, mitigation.RiskId);
        Assert.Equal("Implement Firewall", mitigation.Title);
        Assert.Equal("In Progress", mitigation.Status);
        Assert.Equal(8, mitigation.PlannedEffectiveness);
    }
}

/// <summary>
/// Unit tests for ControlDtos validation and behavior
/// </summary>
public class ControlDtosTests
{
    [Fact]
    public void ControlListItemDto_Create_WithValidData()
    {
        // Arrange
        var id = Guid.NewGuid();
        var controlNumber = "CTRL-001";
        var name = "Firewall - Internet Perimeter";

        // Act
        var control = new ControlListItemDto
        {
            Id = id,
            ControlNumber = controlNumber,
            Name = name,
            Type = "Detective",
            Category = "Technical",
            Status = "Active",
            Effectiveness = "Effective",
            Owner = "IT Security"
        };

        // Assert
        Assert.Equal(id, control.Id);
        Assert.Equal(controlNumber, control.ControlNumber);
        Assert.Equal(name, control.Name);
        Assert.Equal("Detective", control.Type);
        Assert.Equal("Technical", control.Category);
        Assert.Equal("Active", control.Status);
        Assert.Equal("Effective", control.Effectiveness);
    }

    [Fact]
    public void ControlCreateDto_DefaultValues_SetCorrectly()
    {
        // Act
        var control = new ControlCreateDto();

        // Assert
        Assert.Empty(control.Name);
        Assert.Empty(control.Type);
        Assert.Empty(control.Category);
        Assert.Equal("Quarterly", control.TestingFrequency);
        Assert.Equal(0, control.EffectivenessScore);
    }

    [Theory]
    [InlineData("Detective")]
    [InlineData("Preventive")]
    [InlineData("Corrective")]
    public void ControlType_ValidValues_Accepted(string controlType)
    {
        // Act
        var control = new ControlListItemDto { Type = controlType };

        // Assert
        Assert.Equal(controlType, control.Type);
    }

    [Theory]
    [InlineData("Administrative")]
    [InlineData("Technical")]
    [InlineData("Physical")]
    public void ControlCategory_ValidValues_Accepted(string category)
    {
        // Act
        var control = new ControlListItemDto { Category = category };

        // Assert
        Assert.Equal(category, control.Category);
    }

    [Fact]
    public void ControlTestResultDto_Create_WithValidData()
    {
        // Arrange
        var controlId = Guid.NewGuid();

        // Act
        var result = new ControlTestResultDto
        {
            Id = Guid.NewGuid(),
            ControlId = controlId,
            TestDate = DateTime.Now,
            TestType = "Observation",
            Result = "Passed",
            EffectivenessScore = 9
        };

        // Assert
        Assert.Equal(controlId, result.ControlId);
        Assert.Equal("Observation", result.TestType);
        Assert.Equal("Passed", result.Result);
        Assert.Equal(9, result.EffectivenessScore);
    }
}

/// <summary>
/// Unit tests for ReportDtos validation and behavior
/// </summary>
public class ReportDtosTests
{
    [Fact]
    public void ReportListItemDto_Create_WithValidData()
    {
        // Arrange
        var id = Guid.NewGuid();
        var reportNumber = "RPT-2024-001";
        var title = "Q4 2024 Risk Summary Report";

        // Act
        var report = new ReportListItemDto
        {
            Id = id,
            ReportNumber = reportNumber,
            Title = title,
            Type = "Risk",
            Status = "Delivered",
            GeneratedDate = DateTime.Now,
            GeneratedBy = "John Smith",
            PageCount = 18
        };

        // Assert
        Assert.Equal(id, report.Id);
        Assert.Equal(reportNumber, report.ReportNumber);
        Assert.Equal(title, report.Title);
        Assert.Equal("Risk", report.Type);
        Assert.Equal("Delivered", report.Status);
        Assert.Equal(18, report.PageCount);
    }

    [Fact]
    public void ReportCreateDto_DefaultValues_SetCorrectly()
    {
        // Act
        var report = new ReportCreateDto();

        // Assert
        Assert.Empty(report.Title);
        Assert.Empty(report.Type);
        Assert.Empty(report.Description);
        Assert.Empty(report.IncludedEntities);
    }

    [Theory]
    [InlineData("Risk")]
    [InlineData("Compliance")]
    [InlineData("Audit")]
    [InlineData("Dashboard")]
    public void ReportType_ValidValues_Accepted(string reportType)
    {
        // Act
        var report = new ReportListItemDto { Type = reportType };

        // Assert
        Assert.Equal(reportType, report.Type);
    }

    [Fact]
    public void DashboardMetricsDto_Create_WithValidData()
    {
        // Act
        var metrics = new DashboardMetricsDto
        {
            TotalWorkflows = 12,
            ActiveWorkflows = 5,
            CompletedWorkflows = 7,
            OverdueWorkflows = 1,
            TotalAssessments = 8,
            InProgressAssessments = 3,
            TotalAudits = 6,
            OpenAudits = 2,
            TotalRisks = 25,
            CriticalRisks = 2,
            TotalControls = 45,
            EffectiveControls = 38,
            ControlEffectivenessPct = 84.4m,
            LastUpdated = DateTime.Now
        };

        // Assert
        Assert.Equal(12, metrics.TotalWorkflows);
        Assert.Equal(5, metrics.ActiveWorkflows);
        Assert.Equal(8, metrics.TotalAssessments);
        Assert.Equal(25, metrics.TotalRisks);
        Assert.Equal(45, metrics.TotalControls);
        Assert.Equal(84.4m, metrics.ControlEffectivenessPct);
    }
}

/// <summary>
/// Unit tests for Assessment and Audit DTOs (from Phase 7)
/// </summary>
public class AssessmentAndAuditDtosTests
{
    [Fact]
    public void AssessmentListItemDto_Create_WithValidData()
    {
        // Arrange
        var id = Guid.NewGuid();

        // Act
        var assessment = new AssessmentListItemDto
        {
            Id = id,
            AssessmentNumber = "ASMT-SEC-001",
            Name = "Q1 Security Assessment",
            Status = "In Progress",
            Type = "Security",
            AssignedTo = "John Smith",
            Score = 75
        };

        // Assert
        Assert.Equal(id, assessment.Id);
        Assert.Equal("ASMT-SEC-001", assessment.AssessmentNumber);
        Assert.Equal("Q1 Security Assessment", assessment.Name);
        Assert.Equal(75, assessment.Score);
    }

    [Fact]
    public void AuditListItemDto_Create_WithValidData()
    {
        // Arrange
        var id = Guid.NewGuid();

        // Act
        var audit = new AuditListItemDto
        {
            Id = id,
            AuditNumber = "AUD-INT-001",
            Title = "Internal IT Audit",
            Status = "In Progress",
            Type = "Internal",
            FindingCount = 5
        };

        // Assert
        Assert.Equal(id, audit.Id);
        Assert.Equal("AUD-INT-001", audit.AuditNumber);
        Assert.Equal("Internal IT Audit", audit.Title);
        Assert.Equal(5, audit.FindingCount);
    }
}
