using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GrcMvc.Models.Entities
{
    /// <summary>
    /// Individual chat message within a conversation
    /// </summary>
    public class ChatMessage : BaseEntity
    {
        /// <summary>
        /// Foreign key to conversation
        /// </summary>
        [Required]
        public Guid ConversationId { get; set; }

        /// <summary>
        /// Navigation property to conversation
        /// </summary>
        [ForeignKey("ConversationId")]
        public virtual ChatConversation Conversation { get; set; } = null!;

        /// <summary>
        /// Who sent the message: User, Agent, System
        /// </summary>
        [Required]
        [StringLength(20)]
        public string SenderType { get; set; } = "User";

        /// <summary>
        /// Message content (sanitized)
        /// </summary>
        [Required]
        [StringLength(2000)]
        public string Content { get; set; } = string.Empty;

        /// <summary>
        /// Page URL context when message was sent
        /// </summary>
        [StringLength(500)]
        public string? PageUrl { get; set; }

        /// <summary>
        /// Page section/context (e.g., "pricing", "features", "about")
        /// </summary>
        [StringLength(100)]
        public string? PageContext { get; set; }

        /// <summary>
        /// Whether message was generated by AI
        /// </summary>
        public bool IsAiGenerated { get; set; } = false;

        /// <summary>
        /// AI model used (if applicable)
        /// </summary>
        [StringLength(50)]
        public string? AiModel { get; set; }

        /// <summary>
        /// AI confidence score (0-1)
        /// </summary>
        public double? AiConfidence { get; set; }

        /// <summary>
        /// Sentiment analysis result: Positive, Neutral, Negative
        /// </summary>
        [StringLength(20)]
        public string? Sentiment { get; set; }

        /// <summary>
        /// Whether message triggered an escalation
        /// </summary>
        public bool TriggeredEscalation { get; set; } = false;

        /// <summary>
        /// User read the message (for agent messages)
        /// </summary>
        public bool IsRead { get; set; } = false;

        /// <summary>
        /// Timestamp when message was read
        /// </summary>
        public DateTime? ReadAt { get; set; }

        /// <summary>
        /// Additional metadata as JSON
        /// </summary>
        public string? MetadataJson { get; set; }
    }
}
