-- Create user directly in database
-- NOTE: This requires ASP.NET Identity password hashing
-- Better to use the API endpoint once it's available

-- First, let's create the user with a placeholder password hash
-- The password hash will need to be generated by ASP.NET Identity UserManager
-- Password: DogCon@Admin2026

-- For now, we'll need to use the application's UserManager to hash the password
-- This SQL script is a template - actual password hash must come from UserManager

INSERT INTO "AspNetUsers" (
    "Id",
    "FirstName",
    "LastName",
    "Department",
    "JobTitle",
    "UserName",
    "NormalizedUserName",
    "Email",
    "NormalizedEmail",
    "EmailConfirmed",
    "PasswordHash",
    "SecurityStamp",
    "ConcurrencyStamp",
    "PhoneNumber",
    "PhoneNumberConfirmed",
    "TwoFactorEnabled",
    "LockoutEnabled",
    "AccessFailedCount",
    "IsActive",
    "CreatedDate",
    "MustChangePassword",
    "KsaCompetencyLevel"
)
SELECT 
    gen_random_uuid()::text AS "Id",
    'Ahmet' AS "FirstName",
    'Dogan' AS "LastName",
    'Administration' AS "Department",
    'Platform Administrator' AS "JobTitle",
    'ahmet.dogan@doganconsult.com' AS "UserName",
    UPPER('ahmet.dogan@doganconsult.com') AS "NormalizedUserName",
    'ahmet.dogan@doganconsult.com' AS "Email",
    UPPER('ahmet.dogan@doganconsult.com') AS "NormalizedEmail",
    true AS "EmailConfirmed",
    'PLACEHOLDER_HASH_MUST_BE_GENERATED_BY_USERMANAGER' AS "PasswordHash",
    gen_random_uuid()::text AS "SecurityStamp",
    gen_random_uuid()::text AS "ConcurrencyStamp",
    NULL AS "PhoneNumber",
    false AS "PhoneNumberConfirmed",
    false AS "TwoFactorEnabled",
    true AS "LockoutEnabled",
    0 AS "AccessFailedCount",
    true AS "IsActive",
    NOW() AS "CreatedDate",
    true AS "MustChangePassword",
    3 AS "KsaCompetencyLevel"
WHERE NOT EXISTS (
    SELECT 1 FROM "AspNetUsers" WHERE "Email" = 'ahmet.dogan@doganconsult.com'
)
RETURNING "Id", "Email", "FirstName", "LastName";
